# -*- coding: utf-8 -*-
"""plot.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1e8xNb9nMD4d028lId_DXtIhjtwkIyP19
"""
# %%
import os
import numpy as np
import pandas as pd
from matplotlib.pyplot import figure
import matplotlib.pyplot as plt
import time
# %matplotlib inline

# %%
# Commented out IPython magic to ensure Python compatibility.
begin = time.time()
fileat = './Main_Data/kasturi/'
df = pd.read_excel(fileat + 'kasturi vest cog.xlsx')
print(len(df))
X1 = df.iloc[:, :6]
X2 = df.iloc[:, 6:12]

xSca = np.linspace(0, len(df), len(df))
print(len(df['Channel 13']), len(xSca))
plt.figure(1)
plt.scatter(xSca, df['Channel 13'], s=0.4)
#plt.title("Linear graph")
end = time.time()
plt.figure(3)
px1 = X1.plot(subplots=True, figsize=(30, 15),
              grid=True, title=f"_1-6", use_index=True, legend=True)[0]
fig = px1.get_figure()
fig.tight_layout()
fig.subplots_adjust(top=0.95)
#plt.savefig(f"1-6.png", bbox_inches='tight')
plt.show()
print(f"Time Taken {end-begin}")


# %%
# df.plot(subplots=True, figsize=(30, 15), grid=True)
# plt.legend(loc="best")
# #plt.savefig('foo.png', bbox_inches='tight')
# plt.show()
