# -*- coding: utf-8 -*-
"""plot.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1e8xNb9nMD4d028lId_DXtIhjtwkIyP19
"""

import os
import numpy as np
import pandas as pd
from matplotlib.pyplot import figure
import matplotlib.pyplot as plt
# %matplotlib inline

# Commented out IPython magic to ensure Python compatibility.

fileat = './Main_Data/kasturi/'
df = pd.read_excel(fileat + 'kasturi vest cog.xlsx')
df.plot(subplots=True, figsize=(30, 15), grid=True)
plt.legend(loc="best")
plt.savefig('foo.png', bbox_inches='tight')
