# -*- coding: utf-8 -*-
"""plot.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1e8xNb9nMD4d028lId_DXtIhjtwkIyP19
"""
# %%
import os
import numpy as np
import pandas as pd
from matplotlib.pyplot import figure
import matplotlib.pyplot as plt
# %matplotlib inline

# %%
# Commented out IPython magic to ensure Python compatibility.

fileat = './Main_Data/kasturi/'
df = pd.read_excel(fileat + 'kasturi vest cog.xlsx')
print(len(df))
X1 = df.iloc[:, :6]
X2 = df.iloc[:, 6:12]

xSca = np.linspace(0, len(df), len(df))
print(len(df['Channel 13']), len(xSca))
plt.figure(1)
plt.scatter(xSca, df['Channel 13'], s=0.4)
plt.savefig(f"Channel13.png", bbox_inches='tight')
plt.figure(2)
plt.scatter(xSca, df['Channel 14'], s=0.4)
plt.savefig(f"Channel14.png", bbox_inches='tight')
plt.figure(5)
plt.scatter(xSca, df['Channel 13'], s=0.4)
plt.scatter(xSca, df['Channel 14'], s=0.4)
plt.savefig(f"Combine.png", bbox_inches='tight')
plt.figure(3)
X1.plot(subplots=True, figsize=(30, 15), grid=True,)
plt.legend(loc="best")
plt.savefig(f"1-6.png", bbox_inches='tight')
plt.figure(4)
X2.plot(subplots=True, figsize=(30, 15), grid=True)
plt.legend(loc="best")
plt.savefig(f"6-12.png", bbox_inches='tight')


# %%
# df.plot(subplots=True, figsize=(30, 15), grid=True)
# plt.legend(loc="best")
# #plt.savefig('foo.png', bbox_inches='tight')
# plt.show()
